check_one:
  turn_on: false
  output_file: results.csv
  email_length: 7
  email_prefix_int: 9960044

check_many_by_single:
  turn_on: false
  output_file: results.csv
  start_num: 9960044
  end_num: 9960045
  email_length: 7

check_many_by_multi:
  turn_on: false
  output_file: results.csv
  start_num: 9960044
  end_num: 9969999
  email_length: 7
  batch_num: 1000
  process_num: 20

check_many_by_multi_specific:
  turn_on: true
  output_file: results.csv
  # 支持6、7、8、9位
  # 1 表示第一位，[]内表示这一位上可能得数字
  format: {
    1: [ 9 ],
    2: [ 9 ],
    3: [ 6 ],
    4: [ 0,1,2,3,4,5,6,7,8,9 ],
    5: [ 0,1,2,3,4,5,6,7,8,9 ],
    6: [ 0,1,2,3,4,5,6,7,8,9 ],
    7: [ 0,1,2,3,4,5,6,7,8,9 ],
    #    8: [ 0,1,2,3,4,5,6,7,8,9 ],
  }
  batch_num: 1000
  process_num: 20
