version: '3'
services:
  gmail_scanner:
    build:
      context: .
      dockerfile: Dockerfile
    image: klause/gmail_scanner:20230419
    container_name: gmail_scanner
    working_dir: /opt/apps/gmail_scanner
    environment:
      - TZ=Asia/Shanghai
    command: bash -c "sleep 5 && python main.py"
    volumes:
      - $PWD:/opt/apps/gmail_scanner
