version: '3'
services:
  gmail_scanner:
    image: klause/gmail_scanner:latest
    container_name: gmail_scanner
    working_dir: /opt/apps/gmail_scanner
    environment:
      - TZ=Asia/Shanghai
    command: bash -c "sleep 5 && python main.py"
    volumes:
      - ./.env:/opt/apps/gmail_scanner/.env
      - ./results.csv:/opt/apps/gmail_scanner/results.csv
